device: cuda

dataset: 
  name: Hourly
  input_directory: None
  num_obs: 100000

train_parameters:
  max_epochs: 500
  batch_size: 32
  freq_of_test: 5
  learning_rate: 1e-2
  per_series_lr_multip: 1.0
  lr_scheduler_step_size: 7
  lr_decay: 0.5
  level_variability_penalty: 30
  testing_percentile: 50
  training_percentile: 50
  ensemble: False

ES_parameters:
  max_periods: 371
  seasonality: [24, 168]
  input_size: 24
  output_size: 48
  d_input: 25
  d_output: 48
  random_seed: 1

Transformer_parameter:
  d_model: 128
  q: 4
  v: 4
  h: 4
  N: 1
  attention_size: 4
  dropout: 0
  chunk_mode: None 
  pe: None 
  pe_period: 24

