device: cuda

dataset: 
  name: Weekly
  input_directory: None
  num_obs: 100000

train_parameters:
  max_epochs: 500
  batch_size: 32
  freq_of_test: 10
  learning_rate: 1e-2
  per_series_lr_multip: 1.0
  lr_scheduler_step_size: 10
  lr_decay: 0.5
  level_variability_penalty: 100
  testing_percentile: 50
  training_percentile: 50
  ensemble: False

ES_parameters:
  max_periods: 31
  seasonality: []
  input_size: 10
  output_size: 13
  d_input: 16
  d_output: 13
  random_seed: 2

Transformer_parameter:
  d_model: 128
  q: 4
  v: 4
  h: 4
  N: 1
  attention_size: 4
  dropout: 0
  chunk_mode: None 
  pe: None 
  pe_period: 24

