device: cuda

dataset: 
  name: Yearly
  input_directory: None
  num_obs: 100000

train_parameters:
  max_epochs: 500
  batch_size: 4
  freq_of_test: 5
  learning_rate: 1e-4
  per_series_lr_multip: 0.8
  lr_scheduler_step_size: 10
  lr_decay: 0.1
  level_variability_penalty: 100
  testing_percentile: 50
  training_percentile: 50
  ensemble: False

ES_parameters:
  max_periods: 25
  seasonality: []
  input_size: 4
  output_size: 6
  d_input: 10
  d_output: 6
  random_seed: 117982

Transformer_parameter:
  d_model: 128
  q: 4
  v: 4
  h: 4
  N: 1
  attention_size: 4
  dropout: 0
  chunk_mode: None 
  pe: None 
  pe_period: 24

